### PR TITLE
added support for arrow keys in visual modes

### LINKED ISSUE #58: Cursor key support in visual mode
Currently the visual mode is cancelled when using cursor keys, would be great if they were supported.

Context: https://news.ycombinator.com/item?id=11503077

### PR DESCRIPTION
**Pull request by DanEEStar**
This should fix #58 

I took me some time to figure out how all these keys where setup correctly inside of the code.
So please give some remarks if I did something not in a good way.

### CODE REVIEW

**Comment by aioutecism** [comment]
I'm going to check this tonight.

**Comment by aioutecism** [comment]
Sorry @DanEEStar . I was too busy on my company's project these days.
I'm going to review this p-r as soon as possible. Please give me some more time.

**Comment by DanEEStar** [comment]
No problem. Take your time

**Comment by aioutecism** [comment]
Nice work!

**Comment by aioutecism** [comment]
New version published.

**Pull request merged**
