### PR TITLE
Update TypeScript and VSCode dependencies

### PR DESCRIPTION
**Pull request by aioutecism**

### CODE REVIEW

**Comment by alisonatwork** [comment]
@aioutecism while i was playing around with trying to improve the speed of the tests, i tried to bump the various versions of dependencies based on your changes on this PR. My package.json looks like this:

```patch
--- a/package.json
+++ b/package.json
@@ -33,7 +33,7 @@
     "engines": {
         "node": "^8.6.0",
         "npm": "^5.6.0",
-        "vscode": "^1.19.0"
+        "vscode": "^1.32.0"
     },
     "main": "./out/src/extension",
     "extensionKind": [
@@ -258,14 +258,17 @@
         "prettier-write": "prettier --write '{src,test}/**/*.ts'"
     },
     "devDependencies": {
-        "@types/mocha": "^5.2.0",
-        "@types/node": "^8.6.0",
-        "@types/vscode": "^1.19.0",
+        "@types/glob": "^7.1.1",
+        "@types/mocha": "^5.2.6",
+        "@types/node": "^8.10.25",
+        "@types/vscode": "^1.32.0",
         "github-releases-renderer": "github:aioutecism/github-releases-renderer",
-        "mocha": "^5.1.1",
+        "glob": "^7.1.4",
+        "mocha": "^6.1.4",
         "prettier": "^1.19.1",
-        "rimraf": "^2.6.2",
-        "typescript": "^2.8.3",
+        "rimraf": "^2.7.1",
+        "source-map-support": "^0.5.12",
+        "typescript": "^3.5.1",
         "vscode-test": "^1.3.0"
     },
     "dependencies": {}
```

Everything worked fine with the newer Typescript, so i think it's reasonable to go ahead with this upgrade.

**Comment by aioutecism** [comment]
@alisonatwork Thanks! Just checked [Breaking Changes](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes) and everything seems fine. Why don't we update to the latest TS 3.7.3?
And could you please create another PR with your changes?

**Comment by alisonatwork** [comment]
The changes I currently have are on top of the changes inside #258 which makes it a bit tricky. Let me try to put together a PR that just includes the dependency changes, hang on...

**Comment by alisonatwork** [comment]
Here is the new PR for upgrading dependencies: #259  That includes the same changes as this one, plus the change to vscode-test (from vscode) for the latest test harness code.

**Comment by alisonatwork** [comment]
These changes merged in #259

**Pull request closed without merging**
