### PR TITLE
Implemented move backwards to ends

### PR DESCRIPTION
**Pull request by Ddedalus**
Another implementation which seemed easy, I guess you've overlooked it (methods were written already). Does it need unit tests?

### CODE REVIEW

**Comment by jackfranklin** [comment]
@aioutecism is this good to merge or do you want to hold off for tests?

**Comment by aioutecism** [comment]
@jackfranklin I was holding off for tests. Always better to have tests rather than unexpected bugs :)

**Comment by Ddedalus** [comment]
I'm sorry, I can't contribute at the moment (nor in close future :c).
If you have capacity, it would be great to have some tests written :)

**Comment by alisonatwork** [comment]
@aioutecism we can close this now that #255 is merged.

**Comment by aioutecism** [comment]
Done in #255

**Pull request closed without merging**
