### PR TITLE
Support for Word TextObjects "ciw", "caw", "diw", "daw"

### PR DESCRIPTION
**Pull request by DanEEStar**
Implements  #84

### CODE REVIEW

**Comment by mszczepaniak** [comment]
Why there is no merge for it? It's here for 24 days, there are no conflicts with base, c'mon. ciw, caw, diw and daw are great enhancements.

**Comment by DanEEStar** [comment]
rebased to current master

@aioutecism any plans to merge or reject this push request?

**Comment by Beatusvir** [comment]
Thanks @DanEEStar , hope @aioutecism merge this already! :disappointed:

**Comment by aioutecism** [comment]
Sorry for the delay.
I've done some refactoring in #119 , and merged it into master.
Thanks for your contribution!

**Pull request merged**
