### PR TITLE
Support basic text objects

### PR DESCRIPTION
**Pull request by aioutecism**
Continue from #54.

### CODE REVIEW

**Comment by aioutecism** [comment]
@vavans
I did some refactoring.
Cloud you help checking if everything works as expected?

**Comment by vavans** [comment]
Hi, i'll check with my special corner cases as soon as I have access to a computer (maybe Sunday or Monday) i saw you change a lot of things, let me know how I could improve my future contributions (yes, i'm willing to help more if I can ! :) )

**Comment by aioutecism** [comment]
Hi @vavans

I did some test yesterday and I'm going to merge this p-r today. However, further tests are greatly appreciated.

I did refactoring because I found that "text object" is different form "motion".
"Motion" takes a position and returns an adjusted one. While "text object" takes a position and returns a range. Therefore, it's better we create a new "text object" logic layer to deal with text objects.

**Comment by aioutecism** [comment]
I would say there is little advice I can give about coding. All I did is searching and thinking what I'm about to do, and I alway trying to do it the most maintainable way I can.

**Comment by vavans** [comment]
Hi, i tested with my corner cases and everythings is working as expected (same as vi). Nice !

**Comment by aioutecism** [comment]
Great!
Thanks!

**Pull request merged**
