### PR TITLE
Copy to and paste from system clipboard

### LINKED ISSUE #17: y does not yank to clipboard
So now that we've got Ctrl+C, I need a way to copy+paste text between VS:C and other applications. Selection/highlighting only lets me copy 1 line (I'm not sure if this is amVim's fault or VS:C). Pressing y just yanks to some internal clipboard.

Normally in gvim, I would just use selection and middle-click to paste to other applications. Being able to yank to clipboard though would be very useful. I'm just not sure how possible or difficult that is with the underlying technologies.

### LINKED ISSUE #166: p doesn't paste from system clipboard
The ```p``` command doesn't paste from the system clipboard, and there's no equivalent of Vim's ```set clipboard=unnamed```.

How do I paste text I have copied from another application? And can this be made the behaviour of the ```p``` command, either via an option or by default, as it's crucial to me for the "feel" of Vim integrated with Windows.

### PR DESCRIPTION
**Pull request by karlhorky**
Okay, my first try to implement this feature of copying to and pasting from the system clipboard!

Not sure if this is what you meant @aioutecism. Happy to take feedback and improve this still!

I tried changing from `Thenable` to `Promise` to allow for `async` methods on `putAfter` and `putBefore` so that there's not this `.then()` callback hell, but I guess async methods are not supported? Anyway, would love to do this a better way if possible.

This will not overwrite the stash register in case:

1. there is nothing returned from the system clipboard promise  OR...
2. what is in the system clipboard is already in the existing stash

Closes #17
Closes #166

### CODE REVIEW

**Comment by alisonatwork** [comment]
Hey @karlhorky - you might want to experiment with running this on top of the changes from #259 which upgrade the dependencies. I found that upgrading fixed some of the async weirdness i was experiencing with my work on the `gd`/`gD` feature, especially during tests.

**Comment by karlhorky** [comment]
Ping @aioutecism @jackfranklin, could this PR be reviewed?

**Comment by karlhorky** [comment]
@alisonatwork Thanks for the heads up.

Depending on the feedback to both of the PRs, maybe it will make sense to rebase on your changes.

**Comment by karlhorky** [comment]
Hey there @aioutecism @jackfranklin, would you have a chance to take a look at this soon?

**Comment by alisonatwork** [comment]
Hi @karlhorky I just had a first look at the code in this PR, and it seems okay to me on the face of it. To make it a bit easier to manage, could you rebase and force push the branch?

Second question, did you attempt to write a test for this yet? I'm not sure if it's easy to do with the existing test setup, but it would be cool if you could preload the clipboard and config and run something like the `p` test, or do a post-assert in a modified `yy` test.

Regarding your promise problem, I see what you mean by the awkward looking callback. It also makes the diff a bit ugly, having to indent everything. I tried to play around with the order of the code and came up with something like this:

```js
// snip
        if (Configuration.useSystemClipboard === true) {
            return env.clipboard
                .readText()
                .then((result) => {
                    // ...
                    return Promise.resolve(ActionRegister.stash);
                })
                .then((stash) => this._putAfter(args, activeTextEditor, stash));
        }

        return this._putAfter(args, activeTextEditor, ActionRegister.stash);
    }

    private static _putAfter(args, activeTextEditor, stash): Thenable<boolean> {
        if (!stash) {
            return Promise.resolve(false);
        }
// snip
```

This structure would retain most of the indentation from before because it just refactors most of the method into another private method, and it avoids the case where you need to check `Configuration.useSystemClipboard` twice. I'm not sure if it's better or not (and `_putAfter` is probably not a good function name), but it might be something you could play around with and see how it looks in the diff.

**Comment by alisonatwork** [comment]
Looking back at that code snippet i just posted, perhaps it could be simplified to just `return true` in the first `then()`, since we are in native ES6 Promise which should anyway wrap the result into another Promise... And if ActionRegister is global perhaps it doesn't need to be passed into the private function.

**Comment by karlhorky** [comment]
Rebased + force pushed. Now looking into the other feedback...

**Comment by karlhorky** [comment]
> Second question, did you attempt to write a test for this yet?

Just looked into it now. It seems like it needs some more plumbing to do this... right now none of the configuration options have test coverage.

We do however know that it is not causing a regression with the normal clipboard mode (not using the system clipboard), due to the non-option tests.

**Comment by karlhorky** [comment]
So I changed the type of actions to also include Promises (instead of Thenables, which don't allow for async methods), and the code is very clean now.

I found [this reference back in 2015 to async/await in VS Code extensions](https://github.com/Microsoft/vscode/issues/1556), so I guess it's fine like this?

I also tested it out in my VS Code by hot-patching my live extensions folder, and it works :)

**Comment by karlhorky** [comment]
Great, sounds good. Automated testing for options would be a cool thing, maybe I should make an issue for it?

**Comment by alisonatwork** [comment]
Yep, if this is something you'd like to take a look at, that would be great!

**Comment by karlhorky** [comment]
Nice, opened #271 for the test.

And... oops, forgot to add documentation for this option. Opened #272 for this.

Thanks @alisonatwork !

**Pull request merged**
