### PR TITLE
Validate selections when exiting insert mode

### LINKED ISSUE #86: Escaping insert mode leaves normal mode cursor past end of line
Example:
"A Esc"

Adding an ActionSelection.validateSelections() to 'escape' and 'ctrl+c' in ModeInsert should work

### PR DESCRIPTION
**Pull request by ThatLousyGuy**
Fixes #86

### CODE REVIEW

**Comment by aioutecism** [comment]
Oh, I missed this one.
How about call `ActionSelection.validateSelections` on `ModeNormal.enter`?

**Comment by aioutecism** [comment]
On a second thought, call `validateSelections` inside `ModeNormal.enter` may break some behavior.
Do it in `ActionMode.toNormal` should be fine.

```ts
static toNormal(): Thenable<boolean> {
    return commands.executeCommand(`amVim.mode.${ModeID.NORMAL}`)
        .then(() => ActionSelection.validateSelections());
}
```

**Comment by ThatLousyGuy** [comment]
Ah, I was debating whether put the validate in toNormal or in the commands, but I guess I chose the wrong one

**Comment by aioutecism** [comment]
Yes, `toNormal` will only be called intentionally, so validate selections there should be fine.
Would you mind do to modification so I can merge this p-r?

**Comment by ThatLousyGuy** [comment]
Sorry, I got a little busy. It's done, could you help me squash and merge?

**Comment by aioutecism** [comment]
Great! Thanks for the contribution.

**Pull request merged**
